# Generated by Django 2.2.6 on 2019-12-01 17:53

from django.db import migrations, models
import uniServe.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('uniCategory', models.IntegerField(choices=[(uniServe.models.UniCategory(0), 0), (uniServe.models.UniCategory(1), 1), (uniServe.models.UniCategory(2), 2), (uniServe.models.UniCategory(3), 3), (uniServe.models.UniCategory(4), 4), (uniServe.models.UniCategory(5), 5)])),
            ],
        ),
    ]
