# Generated by Django 2.2.6 on 2019-12-01 19:55

from django.db import migrations, models
import uniServe.models


class Migration(migrations.Migration):

    dependencies = [
        ('uniServe', '0002_auto_20191201_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='ProfileImages/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='imageBytes',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='loginType',
            field=models.IntegerField(blank=True, choices=[(uniServe.models.LoginType(0), 0), (uniServe.models.LoginType(1), 1), (uniServe.models.LoginType(2), 2)], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='unisAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='userType',
            field=models.IntegerField(blank=True, choices=[(uniServe.models.UserType(0), 0), (uniServe.models.UserType(1), 1), (uniServe.models.UserType(2), 2), (uniServe.models.UserType(3), 3), (uniServe.models.UserType(4), 4)], null=True),
        ),
    ]
