# Generated by Django 2.2.6 on 2019-12-01 21:39

from django.db import migrations
import django_enumfield.db.fields
import uniServe.models


class Migration(migrations.Migration):

    dependencies = [
        ('uniServe', '0003_auto_20191201_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='loginType',
            field=django_enumfield.db.fields.EnumField(default=2, enum=uniServe.models.LoginType),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userType',
            field=django_enumfield.db.fields.EnumField(default=1, enum=uniServe.models.UserType),
        ),
        migrations.AlterField(
            model_name='uniar',
            name='uniCategory',
            field=django_enumfield.db.fields.EnumField(default=1, enum=uniServe.models.UniCategory),
        ),
        migrations.AlterField(
            model_name='uniar',
            name='uniFileType',
            field=django_enumfield.db.fields.EnumField(default=3, enum=uniServe.models.UniFileType),
        ),
        migrations.AlterField(
            model_name='uniar',
            name='uniType',
            field=django_enumfield.db.fields.EnumField(default=2, enum=uniServe.models.UniType),
        ),
    ]
