# Generated by Django 2.2.6 on 2019-12-01 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniServe', '0004_auto_20191201_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/ProfileImages/'),
        ),
        migrations.AlterField(
            model_name='uniar',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='static/files/'),
        ),
        migrations.AlterField(
            model_name='uniar',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
