# Generated by Django 2.2.6 on 2019-12-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniServe', '0006_auto_20191201_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers_user',
            field=models.ManyToManyField(related_name='follows', to='uniServe.Profile'),
        ),
    ]
