# Generated by Django 2.2.6 on 2019-12-03 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniServe', '0007_profile_followers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers_user',
            field=models.ManyToManyField(related_name='_profile_followers_user_+', to='uniServe.Profile'),
        ),
    ]
