# Generated by Django 2.2.6 on 2019-12-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uniServe', '0008_auto_20191202_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='followers_user',
            field=models.ManyToManyField(related_name='follows', to='uniServe.Profile'),
        ),
    ]
